import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Hero from '@/Components/Hero/Hero'
import Content from '@/Components/Content/Content'
import Footer from '@/Components/Footer/Footer'
import NavTest from '@/Components/Navbar/Navtest'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NavTest />
        <Hero />
        <Content />
        <Footer />
      </main>
    </>
  )
}
